services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /docker/appdata/tautulli:/config
    environment:
      - PUID=3002
      - PGID=3000
      - TZ=Canada/Atlantic
    ports:
      - 8181:8181
