---
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - /docker/appdata/uptimekuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
