---
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=2001
      - PGID=2000
      - UMASK=002
      - TZ=Canada/Atlantic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=2002
      - PGID=2000
      - UMASK=002
      - TZ=Canada/Atlantic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=2003
      - PGID=2000
      - UMASK=002
      - TZ=Canada/Atlantic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=2004
      - PGID=2000
      - TZ=Canada/Atlantic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    user: 2005:2000
    environment:
      - LOG_LEVEL=debug
      - TZ=Canada/Atlantic
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/seerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    environment:
      - SECRET_ENCRYPTION_KEY=b2c6b47fcd2ee62a6089cf6b9ece85805a87d801a74b5c9d459e026edfdbf156
      - PUID=2006
      - PGID=2000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/homarr:/appdata
    ports:
      - 7575:7575
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    environment:
      - SECRET_ENCRYPTION_KEY=(GO to https://homarr.dev/docs/getting-started/installation/docker)
      - PUID=2006
      - PGID=2000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/homarr:/appdata
    ports:
      - 7575:7575
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8191:8191"
