---
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=5000
      - PGID=5000
      - TZ=Canada/Atlantic
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi-db
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
#      - MEM_STARTUP=1024 #optional
#      - MONGO_TLS= #optional
    volumes:
      - /docker/appdata/unifi-network-application/data:/config
    networks:
      unifi-macvlan:
        ipv4_address: 10.13.37.11
    restart: unless-stopped

  unifi-db:
    image: docker.io/mongo:8.0.5
    container_name: unifi-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=unifi
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - /docker/appdata/unifi-db/data:/data/db
      - /docker/appdata/unifi-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      unifi-macvlan:
        ipv4_address: 10.13.37.12
    restart: unless-stopped

networks:
  unifi-macvlan:
    external: true
    name: unifi-macvlan
